name: Automation Tests

on:
workflow_dispatch:
schedule:
  - cron: 30 2 * * *
  - cron: 0 1 * * *

jobs:
  ui-chrome-qa-tests:
    runs-on: ubuntu-latest
    steps:
      - name: QA
        uses: actions/checkout@v2
        if: github.event.schedule == '30 2 * * *'
        with:
          command: npm run qa-test
  ui-chrome-uat-tests:
    runs-on: ubuntu-latest
    steps:
      - name: UAT
        uses: actions/checkout@v2
        if: github.event.schedule != '30 2 * * *'
        with:
          command: npm run uat-test